# Copyright 2018, Oracle Corporation and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "TRAEFIK" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-traefik
  namespace: {{ .Values.wlsDomain.namespace }}
  labels:
    weblogic.resourceVersion: traefik-load-balancer-v1
spec:
  annotations:
    kubernetes.io/ingress.class: traefik
  rules:
  - host: '{{ .Values.traefik.hostname }}'
    http:
      paths:
      - path:
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower }}'
          servicePort: {{ .Values.wlsDomain.managedServerPort }}
{{- end }}
